apiVersion: v1
kind: ServiceAccount
metadata:
  name: fournos-dashboard
  annotations:
    serviceaccounts.openshift.io/oauth-redirectreference.fournos: '{"kind":"OAuthRedirectReference","apiVersion":"v1","reference":{"kind":"Route","name":"fournos-dashboard"}}'
