apiVersion: v1
kind: Namespace
metadata:
  name: fournos-controller
  labels:
    app.kubernetes.io/part-of: fournos
---
apiVersion: v1
kind: Namespace
metadata:
  name: psap-automation
  labels:
    app.kubernetes.io/part-of: fournos
    fournos.dev/queue-access: "true"
    argocd.argoproj.io/managed-by: openshift-gitops
---
apiVersion: v1
kind: Namespace
metadata:
  name: psap-secrets
  labels:
    app.kubernetes.io/part-of: fournos
